# Generated by Django 5.2.5 on 2025-10-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('degree', models.CharField(blank=True, max_length=200, null=True)),
                ('specialty', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=5)),
                ('review_count', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='doctors/')),
                ('profile_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
