# Generated by Django 5.2.5 on 2025-10-28 10:57

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorclinic',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=27, null=True),
        ),
    ]
