# Generated by Django 5.2.5 on 2025-10-29 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteApp', '0002_alter_doctorclinic_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorclinic',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_doctors', to='WebsiteApp.clinic'),
        ),
        migrations.AlterField(
            model_name='doctorclinic',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_clinics', to='WebsiteApp.doctor'),
        ),
    ]
