# Generated by Django 5.2.5 on 2025-10-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteApp', '0003_remove_doctor_degree_remove_doctor_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
