# Generated by Django 5.2.5 on 2025-10-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteApp', '0004_doctor_qualification_doctor_rating_doctor_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=200)),
                ('qualification', models.CharField(default='Unknown', max_length=200)),
                ('email', models.EmailField(default='unknown@example.com', max_length=254)),
                ('phone', models.CharField(default='0000000000', max_length=15)),
                ('address', models.CharField(default='Unknown', max_length=255)),
                ('image', models.ImageField(default='doctor/default.jpg', upload_to='doctor/')),
                ('experience_years', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('reviews', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
