# Generated by Django 5.2.5 on 2025-10-27 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteApp', '0006_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='description',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='specialization',
        ),
        migrations.AddField(
            model_name='clinic',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to='WebsiteApp.city'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='image',
            field=models.ImageField(upload_to='clinic_images/'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
