# Generated by Django 5.2.5 on 2025-10-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteApp', '0008_category_service_doctor_city_doctor_clinic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='category',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='clinic',
        ),
        migrations.AddField(
            model_name='doctor',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='WebsiteApp.address'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='WebsiteApp.category'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinics',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='WebsiteApp.clinic'),
        ),
    ]
